version: 2

sources:
  - name: raw_data_circle
    description: data sources from circle sales and stock
    tables:
      - name: raw_cc_stock
        description: stock of products
        columns:
          - name: model
            description: ID of model
      - name: raw_cc_sales
        description: sales of products
        tests:
           - unique:
              column_name: "(product_id || '-' || date_date)"